### ISSUE TITLE
A great article, wish it could be used to configure roles on the actions

### ISSUE THREAD

**Issue by papyr** [Haacked/CodeHaacks#11]
Hello, I was wondering if you could help out, since this is really the only decent actions and controllers lister-thinamgigy :)

can you please give me an idea on how I could apply roles to the actions (i am using identity v 2.1  with asp mvc 4.52)

thanks

**Comment by Haacked** [comment]
If you mean you want to restrict actions to certain roles, use the `AuthorizeAttribute` and set the `Roles` property. See an example here: https://msdn.microsoft.com/en-us/library/system.web.mvc.authorizeattribute.roles(v=vs.118).aspx#P:System.Web.Mvc.AuthorizeAttribute.Roles

**Comment by papyr** [comment]
Hi sorry for not being clear, how can I configure the Role to <->  Controller-Actions Mapping, currently its done in a static way in the code. I would like to capture this in the DB or configfile and let Admin user in the view, select which roles have which permission.

**Comment by Haacked** [comment]
Ah! There's nothing built in to do that. In theory it's possible because of the extensibility model. Perhaps something like this would help. http://stackoverflow.com/questions/30099613/dynamically-add-roles-to-authorize-attribute-for-controller
